# Generated by Django 4.2.5 on 2024-02-04 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfuploader', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordCloud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_cloud', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
